# fly.toml app configuration file generated for fxt on 2023-11-03T10:07:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fxt"
primary_region = "sjc"

[build]

[deploy]
  strategy = "immediate"
